#!/usr/bin/env bash
# This script is run after your app is installed.
APP_NAME="Omnis Studio Runtime 10.0" # Customize with your app name
COMANY_NAME="Omnis" # Customize with the CORE_RES_25599 entry from Contents/Resources/English.lproj/Localizable.strings

APP_ROOT="/Applications/${APP_NAME}.app"
COMPANY_APP_SUPPORT="${HOME}/Library/Application Support/${COMANY_NAME}"
APP_SUPPORT="${COMPANY_APP_SUPPORT}/${APP_NAME}"

# Setup permissions
sudo chmod -R a+r "${APP_ROOT}/Contents/MacOS/"

# Un-comment if you use BrainyPDF
# sudo chmod a+rw ../MacOS

# Frameworks
sudo chmod -R 755 "${APP_ROOT}/Contents/Frameworks/*.dylib"

# Remove existing app support folder
if [ -d "${APP_SUPPORT}" ]; then
	rm -r "${APP_SUPPORT}"
fi

# Pre-create new app support folder
if [ ! -d "${COMPANY_APP_SUPPORT}" ]; then
	mkdir -p "${COMPANY_APP_SUPPORT}"
fi

cp -r "${APP_ROOT}/Contents/MacOS/firstruninstall" "${APP_SUPPORT}"
sudo chown -R "${USER}" "${COMPANY_APP_SUPPORT}"